// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI5hvN-Hi66iBbiryAmG9ySGNFGVEKZUI',
    appId: '1:623111982057:web:557c2af6b4e45fabd65978',
    messagingSenderId: '623111982057',
    projectId: 'bchms-216c5',
    authDomain: 'bchms-216c5.firebaseapp.com',
    storageBucket: 'bchms-216c5.firebasestorage.app',
    measurementId: 'G-976G30TGK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0EwzQwI9iN404SXAuuThHz4FsQavsvtY',
    appId: '1:623111982057:android:2c653c1aa6ce12c5d65978',
    messagingSenderId: '623111982057',
    projectId: 'bchms-216c5',
    storageBucket: 'bchms-216c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEjSggdwTeF-gsTxDcxIWCYK_VnpTU2kw',
    appId: '1:623111982057:ios:d3f19ca23f770d29d65978',
    messagingSenderId: '623111982057',
    projectId: 'bchms-216c5',
    storageBucket: 'bchms-216c5.firebasestorage.app',
    iosBundleId: 'com.example.bchms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEjSggdwTeF-gsTxDcxIWCYK_VnpTU2kw',
    appId: '1:623111982057:ios:d3f19ca23f770d29d65978',
    messagingSenderId: '623111982057',
    projectId: 'bchms-216c5',
    storageBucket: 'bchms-216c5.firebasestorage.app',
    iosBundleId: 'com.example.bchms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI5hvN-Hi66iBbiryAmG9ySGNFGVEKZUI',
    appId: '1:623111982057:web:920439e071f92941d65978',
    messagingSenderId: '623111982057',
    projectId: 'bchms-216c5',
    authDomain: 'bchms-216c5.firebaseapp.com',
    storageBucket: 'bchms-216c5.firebasestorage.app',
    measurementId: 'G-R482YE1EZ2',
  );
}
